name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.18"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go generate ./...
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: goimports -w .
      - run: git diff --cached --exit-code
      - run: go test ./...
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
